# Generated by Django 5.1.5 on 2026-09-28 23:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0002_milestone_task_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='créé le')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='modifié le')),
                ('event_type', models.CharField(db_index=True, max_length=48, verbose_name='événement')),
                ('group_key', models.CharField(max_length=120, verbose_name='clé de regroupement')),
                ('dedupe_key', models.CharField(blank=True, help_text="Un même événement ne notifie qu'une fois.", max_length=160, verbose_name="clé d'unicité")),
                ('title', models.CharField(max_length=200, verbose_name='titre')),
                ('body', models.CharField(blank=True, max_length=500, verbose_name='détail')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='événements regroupés')),
                ('data', models.JSONField(blank=True, default=dict, verbose_name='données')),
                ('last_event_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='dernier événement')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='lue le')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='projects.project', verbose_name='projet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='destinataire')),
            ],
            options={
                'verbose_name': 'notification',
                'verbose_name_plural': 'notifications',
                'ordering': ['-last_event_at', '-id'],
                'indexes': [models.Index(fields=['user', 'read_at', '-last_event_at'], name='notificatio_user_id_c983e9_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('read_at__isnull', True)), fields=('user', 'group_key'), name='uniq_open_notification_per_group'), models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('user', 'dedupe_key'), name='uniq_notification_dedupe_key')],
            },
        ),
    ]
